on:
  push:
    branches:
      - main
    paths-ignore:
      - 'infrastructure/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Yarn Install
        run: |
          yarn install

      - name: Staging Build
        run: |
          yarn build

      - name: Unit Tests
        run: |
          yarn test

      - name: Generate AWS Token
        run: |
          curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
        env:
          AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awscreds

      - name: Copy build to S3
        run: |
          aws s3 sync build s3://criblsizing.info --delete
        env:
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
          AWS_REGION: us-east-1
          AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awscreds
